language: node_js
node_js:
  - "4.0"
install:
- npm install elm
- npm install elm-test
- elm-package install -y
script:
- bin/fetch-configlet
- bin/configlet .
- node_modules/.bin/elm-test TestRunner.elm
